spring:
    thymeleaf:
        cache: false
        check-template-location: true
        prefix: classpath:/templates/

mail:
    sendgrid:
        api: 
    from: metaclip@metaclip.org
    to: 
    
github-repo: https://raw.githubusercontent.com/metaclip/vocabularies/master/
github-repo-devel: https://raw.githubusercontent.com/metaclip/vocabularies/devel/

metaclip:
    uri: 'http://www.metaclip.org/'
    prefixes:
        "[http://www.metaclip.org/datasource/datasource.owl#]": "ds"
        "[http://www.metaclip.org/verification/verification.owl#]": "vr"
        "[http://www.metaclip.org/calibration/calibration.owl#]": "cl"
        "[http://www.metaclip.org/graphical_output/graphical_output.owl#]": "gp"
        "[http://www.metaclip.org/ipcc_terms/ipcc_terms.owl#]": "ipcc"
        "[http://purl.org/dc/elements/1.1/#]": "dc"
        "[http://www.w3.org/ns/prov#]": "prov"
        "[http://www.w3.org/2000/01/rdf-schema#]": "rdf"
        "[http://www.opengis.net/ont/geosparql#]": "geo"
        "[http://www.w3.org/2002/07/owl#]": "owl"
    groups:
        "[ds:ENSO]": "datasource-details"
        "[ds:Argument]": "command"
        "[ds:DatasetSubset]": "datasource"
        "[ds:Initialization]": "datasource-details"
        "[ds:TemporalResolution]": "datasource-details"
        "[ds:GCM]": "datasource-details"
        "[ds:PCA]": "datasource-details"
        "[ds:Project]": "datasource"
        "[ds:DatasetVersion]": "datasource-details"
        "[ds:Longitude]": "datasource-details"
        "[ds:Realization]": "datasource-details"
        "[ds:Member]": "datasource-details"
        "[ds:ObservationalDataset]": "datasource"
        "[ds:ClimateIndex]": "datasource"
        "[ds:ClimateIndexDefinition]": "datasource"
        "[ds:ClimateIndexCalculation]": "datasource"
        "[ds:Index]": "datasource"
        "[ds:IndexDefinition]": "datasource"
        "[ds:IndexCalculation]": "datasource"
        "[ds:Dataset]": "datasource"
        "[ds:ValidationTime]": "datasource-details"
        "[ds:ArgumentValue]": "command"
        "[ds:ETCCDI]": "datasource"
        "[ds:RCM]": "datasource"
        "[ds:Dimension]": "datasource-details"
        "[ds:Aggregation]": "datasource"
        "[ds:TemporalInstant]": "datasource-details"
        "[ds:NAO]": "datasource-details"
        "[ds:Regridding]": "datasource"
        "[ds:Interpolation]": "datasource"
        "[ds:ModellingCenter]": "datasource-details"
        "[ds:MultiDecadalSimulation]": "datasource"
        "[ds:Step]": "datasource"
        "[ds:Latitude]": "datasource-details"
        "[ds:Climatology]": "datasource"
        "[ds:Experiment]": "datasource"
        "[ds:InterpolationMethod]": "datasource"
        "[ds:NearestNeighbor]": "datasource"
        "[ds:BicubicInterpolation]": "datasource"
        "[ds:BilinearInterpolation]": "datasource"
        "[ds:InverseDistanceWeighting]": "datasource"
        "[ds:Splines]": "datasource"
        "[ds:Command]": "command"
        "[ds:SeasonalOperationalForecast]": "datasource"
        "[ds:VariableStandardDefinition]": "datasource"
        "[ds:TemporalPeriod]": "datasource"
        "[ds:Anomaly]": "datasource"
        "[ds:DifferenceAnomaly]": "datasource"
        "[ds:RelativeAnomaly]": "datasource"
        "[ds:ENSOregion]": "datasource"
        "[ds:SeasonalForecastingSystem]": "datasource"
        "[ds:Package]": "command"
        "[ds:ShortRangeForecast]": "datasource"
        "[ds:ENSOregion]": "datasource-details"
        "[ds:SeasonalHindcast]": "datasource"
        "[ds:Transformation]": "datasource"
        "[ds:DataProvider]": "datasource-details"
        "[ds:Variable]": "datasource"
        "[ds:SpatialExtent]": "datasource-details"
        "[ds:HorizontalExtent]": "datasource-details"
        "[ds:VerticalExtent]": "datasource-details"
        "[ds:Reanalysis]": "datasource"
        "[vr:Resolution]": "verification"
        "[vr:Validation]": "verification"
        "[vr:ForecastVerification]": "verification"
        "[vr:Accuracy]": "verification"
        "[vr:Ensemble]": "verification"
        "[vr:MulticategoryProbability]": "verification"
        "[vr:Association]": "verification"
        "[vr:Discrimination]": "verification"
        "[vr:SkillScore]": "verification"
        "[vr:ForecastRepresentation]": "verification"
        "[vr:Reliability]": "verification"
        "[vr:Verification]": "verification"
        "[vr:Bias]": "verification"
        "[vr:ContinuousProbability]": "verification"
        "[vr:BinaryProbability]": "verification"
        "[vr:QualityAspect]": "verification"
        "[vr:DeterministicContinuous]": "verification"
        "[cl:ProbabilityScaling]": "calibration"
        "[cl:ESD-MOS]": "calibration"
        "[cl:Analogs]": "calibration"
        "[cl:EnsembleRecalibration]": "calibration"
        "[cl:LinearScaling]": "calibration"
        "[cl:QQMapping]": "calibration"
        "[cl:ESD]": "calibration"
        "[cl:TransferFunctions]": "calibration"
        "[cl:CCA]": "calibration"
        "[cl:BiasAdjustment]": "calibration"
        "[cl:BiasCorrection]": "calibration"
        "[cl:Calibration]": "calibration"
        "[cl:NPQuantileMapping]": "calibration"
        "[cl:PQuantileMapping]": "calibration"
        "[cl:VarianceInflation]": "calibration"
        "[cl:ESD-PP]": "calibration"
        "[cl:calibration]": "calibration"
        "[cl:WeatherTyping]": "calibration"
        "[gp:graphicalProduct]": "graphical"
        "[gp:GraphicalProduct]": "graphical"
        "[gp:MultiGraphicalProduct]": "graphical"
        "[gp:ChartPoints]": "graphical"
        "[gp:ChartRaster]": "graphical"
        "[gp:Chart]": "graphical"
        "[gp:ObservationalUncertainty]": "graphical"
        "[gp:SamplingUncertainty]": "graphical"
        "[gp:SpatialChartAxis]": "graphical"
        "[gp:ProbabilityChartAxis]": "graphical"
        "[gp:ChartLines]": "graphical"
        "[gp:ChartLayer]": "graphical"
        "[gp:MagnitudeChartAxis]": "graphical"
        "[gp:TextLayer]": "graphical"
        "[gp:ForecastSystemUncertainty]": "graphical"
        "[gp:MapLayer]": "graphical"
        "[gp:Layer]": "graphical"
        "[gp:MapPoints]": "graphical"
        "[gp:ChartPolygons]": "graphical"
        "[gp:TimeChartAxis]": "graphical"
        "[gp:TransformationUncertainty]": "graphical"
        "[gp:Mask]": "graphical"
        "[gp:Map]": "graphical"
        "[gp:MapRaster]": "graphical"
        "[gp:Uncertainty]": "graphical"
        "[gp:ChartAxis]": "graphical"
        "[gp:MapPolygons]": "graphical"
        "[gp:MapLines]": "graphical"
